### ISSUE TITLE
Invalid Path

### ISSUE THREAD

**Issue by knxroot** [cweijan/autohotkey-plus#1]
Apparently it doesn't work using AHk version 1.1.32.00, I did a clean installation of Windows 10 + AHK 1.1.32 + VSCODE and its extension and after trying to do a hello world it is observed that it does not recognize the default interpreter.

![Invalid_path](https://user-images.githubusercontent.com/865231/77860847-db5e5d00-71e7-11ea-9502-8958d013734b.png)

The path is valid, I check and I configure follow the instructions.

**Comment by cweijan** [comment]
My AHK version is the same 1.1.32.00, it's work.
Give me your execute configuration path.

**Comment by knxroot** [comment]
"C:\Program Files\AutoHotkey\AutoHotkeyU64.exe" Version is 1.1.32.00 Windows 10 Profesional . I installed VSCODE and AHK in their default configuration. Do you take any additional steps?

**Comment by cweijan** [comment]
update to 2.2.4 try again.

**Comment by knxroot** [comment]
It works, Thanks!
