### ISSUE TITLE
Showing additional information about objects

### ISSUE THREAD

**Issue by helperman** [cweijan/autohotkey-plus#12]
Is it possible to show more relevant information about objects?
Try to debug this code for example:
```
for procData in ComObjGet("winmgmts:").ExecQuery("SELECT * FROM Win32_Process WHERE name = 'explorer.exe'")
{
	cmd := procData.CommandLine
	OutputDebug cmd: %cmd%
}
```

Expected: commandLine value as well as all the fields from the link below are shown in a list of variables of the procData variable:
https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-process

Actual: four items are shown (Value, VarType, DispatchType, DispatchIID).

![005](https://user-images.githubusercontent.com/8351863/83297770-d58ef300-a1fb-11ea-994a-bdf954afe94d.jpg)

**Comment by cweijan** [comment]
Unfortunately, the debug program only returns these four properties, so this is impossible, since 2.4.0, which supports OutputDebug printing in the console, may improve your development experience.

**Comment by cweijan** [comment]
I did some experiments and found that it is indeed not supported.
