### ISSUE TITLE
Ahk2Exe path change

### ISSUE THREAD

**Issue by AlexandrShpv** [cweijan/autohotkey-plus#13]
Where can I change Ahk2Exe.exe location path to my D:/AutoHotkey_1.1.30.01/Compiler/Ahk2Exe.exe? Thanks.
![ahk2exe](https://user-images.githubusercontent.com/34154387/83335091-ffefb780-a2b2-11ea-926a-4f2704c6305c.gif)

**Comment by cweijan** [comment]
1. Press "Ctrl+Shift+P" to open command palette.
2. Input "Config Ahk" to select config command. 
3. config your path

**Comment by AlexandrShpv** [comment]
1. I changed AHK: Confiq Ahk Execute Bin Path to D:\AutoHotkey_1.1.30.01\AutoHotkeyU64.exe and Debug Ahk Script work fine.
2. Compile Script path remain C:/Program Files/autoHotkey/Compiler/Ahk2Exe.exe

It is possible edit file ScriptRunner.ts before extention installation? Sorry if the question is stupid.
I'm very beginner.
![scriptruner](https://user-images.githubusercontent.com/34154387/83336039-4e07b980-a2b9-11ea-80a0-f7ab1efda0b2.gif)

**Comment by cweijan** [comment]
Ok, it's my mistake.

**Comment by cweijan** [comment]
update to 2.4.1, looking for https://github.com/cweijan/vscode-autohotkey#setting

**Comment by AlexandrShpv** [comment]
Now it works great!
