### ISSUE TITLE
CodeFormat doesn't follow indent setting.

### ISSUE THREAD

**Issue by TTSKarlsson** [cweijan/autohotkey-plus#14]
Setting the indent for AutoHotkey files to anything else than 4 spaces fails.

**Recreate:** Set indent to 2 spaces.

**Result:** Indents 4 spaces.
![image](https://user-images.githubusercontent.com/9962943/85276257-ceb57200-b481-11ea-83fe-b9e3746b0e43.png)

**Expected result:** Indenting 2 spaces.

_Preferred solutions:_
_1. Use the indent settings for the file type. , or..
2. Make an extension setting for it._

// Big thanks for a nice extension!

**Comment by cweijan** [comment]
This is indeed a bug, I will fix it in the next few days

**Comment by cweijan** [comment]
Fix at version 2.4.2.

**Comment by TTSKarlsson** [comment]
Awesome , thank you!
