### ISSUE TITLE
Recent update introduced syntax bug?

### ISSUE THREAD

**Issue by RB490** [cweijan/autohotkey-plus#15]
previous:

![image](https://user-images.githubusercontent.com/13181077/85861598-e9108800-b7c0-11ea-877b-f119575cdb21.png)

current:

![image](https://user-images.githubusercontent.com/13181077/85861644-f9286780-b7c0-11ea-93c7-29ec6c4f40a3.png)

theme: https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme

**Comment by RB490** [comment]
Having both autohotkey extensions enabled also fixes it
slevesque.vscode-autohotkey
cweijan.vscode-autohotkey-plus

**Comment by cweijan** [comment]
I will fix the bug in the next version.

**Comment by RB490** [comment]
Appreciated :)

**Comment by cweijan** [comment]
New version has bean release.

**Comment by RB490** [comment]
Fixed!
