### ISSUE TITLE
Syntax highlighting bug involving quotes

### ISSUE THREAD

**Issue by RB490** [cweijan/autohotkey-plus#16]
correct: 
![image](https://user-images.githubusercontent.com/13181077/86056697-1fb6fe80-ba5e-11ea-87c9-df9d85b85a4f.png)

bugged:

![image](https://user-images.githubusercontent.com/13181077/86056709-25acdf80-ba5e-11ea-864f-7ffab603b58b.png)

```
msgbox % A_ThisLabel ": text inside quotes" text outside quotes
msgbox, 4160, , % A_ThisLabel ": text inside quotes" text outside quotes
```

**Comment by cweijan** [comment]
Update to 2.4.5 fix.

**Comment by RB490** [comment]
Fixed!
