### ISSUE TITLE
Switch cases are detected as labels in outline view and breadcrumbs

### ISSUE THREAD

**Issue by RB490** [cweijan/autohotkey-plus#18]
Outline
![image](https://user-images.githubusercontent.com/13181077/86539741-5037e600-beff-11ea-806c-dcff84e86289.png)

Breadcrumbs
![image](https://user-images.githubusercontent.com/13181077/86539752-6645a680-beff-11ea-855b-4fe692951e14.png)

**Comment by cweijan** [comment]
Update to 2.4.7 fix.

**Comment by RB490** [comment]
Thanks :)
