### ISSUE TITLE
Comment block autocomplete ignores indentation

### ISSUE THREAD

**Issue by RB490** [cweijan/autohotkey-plus#19]
Current:

![image](https://user-images.githubusercontent.com/13181077/86614936-0d841580-bfb4-11ea-8aa7-52b6dd6f5f9f.png)

Desired:

![image](https://user-images.githubusercontent.com/13181077/86614968-1543ba00-bfb4-11ea-983a-8f89b846c435.png)

**Comment by cweijan** [comment]
Due to the limitation of vscode, the indent cannot be automatically generated.

**Comment by RB490** [comment]
Understandable
