### ISSUE TITLE
Strange indent

### ISSUE THREAD

**Issue by ainfkcn** [cweijan/autohotkey-plus#2]
I copyed some example from ahk's doc and wrote a little bit of myself. After formating, it was like this.
![Snipaste_2020-03-30_13-24-32](https://user-images.githubusercontent.com/37947454/77878507-08178080-728b-11ea-871b-cbde0c138597.jpg)

I think it is natural that the _#IfWinActive_ in line 11 at the same position as line 7, _::btw::_ in line 10 at the same position as line 9 and _#c::_ in line 12 alse at the same position as line 7.

**Comment by ainfkcn** [comment]
Oh, I just found out this problem is caused by the _MsgBox_. The format is fine If change all the Msgbox sentence to other sentence.

**Comment by greenmooseSE** [comment]
@cweijan Will above also fix formatting below? (I would expect every ```#IfWinActive``` reset indent )
From ahk docs:
```ahk
#IfWinActive ahk_class Notepad
^!c::MsgBox You pressed Control+Alt+C in Notepad.
#IfWinActive ahk_class WordPadClass
^!c::MsgBox You pressed Control+Alt+C in WordPad.
#IfWinActive
^!c::MsgBox You pressed Control+Alt+C in a window other than Notepad/WordPad.
```
Reformatted in vscode:
```ahk
#IfWinActive ahk_class Notepad
    ^!c::MsgBox You pressed Control+Alt+C in Notepad.
    #IfWinActive ahk_class WordPadClass
        ^!c::MsgBox You pressed Control+Alt+C in WordPad.
    #IfWinActive
    ^!c::MsgBox You pressed Control+Alt+C in a window other than Notepad/WordPad.
```
What I would expect:
```ahk
#IfWinActive ahk_class Notepad
    ^!c::MsgBox You pressed Control+Alt+C in Notepad.
#IfWinActive ahk_class WordPadClass
    ^!c::MsgBox You pressed Control+Alt+C in WordPad.
#IfWinActive
    ^!c::MsgBox You pressed Control+Alt+C in a window other than Notepad/WordPad.
```

**Comment by cweijan** [comment]
@greenmooseSE  you need close code block like below.
```ahk
#IfWinActive ahk_class Notepad
    ^!c::MsgBox You pressed Control+Alt+C in Notepad.
#IfWinActive

#IfWinActive ahk_class WordPadClass
    ^!c::MsgBox You pressed Control+Alt+C in WordPad.
#IfWinActive

^!c::MsgBox You pressed Control+Alt+C in a window other than Notepad/WordPad.
```
