### ISSUE TITLE
Function overview pop up bug

### ISSUE THREAD

**Issue by RB490** [cweijan/autohotkey-plus#21]
![image](https://user-images.githubusercontent.com/13181077/86908320-a468e300-c116-11ea-8856-10e033bfc892.png)

'title' is missing a " and wrong colour
'text1' is missing entirely

**Comment by cweijan** [comment]
Update to 2.4.9.

**Comment by RB490** [comment]
Issue does not seem to be fixed on 2.4.9
![image](https://user-images.githubusercontent.com/13181077/87188637-7b4f7a80-c2ef-11ea-9f90-56e0e93d2fb6.png)

incorrect with 2 optional parameters or more
![image](https://user-images.githubusercontent.com/13181077/87188723-9cb06680-c2ef-11ea-884c-815a72142a83.png)

correct with 1 optional parameter
![image](https://user-images.githubusercontent.com/13181077/87188812-c6698d80-c2ef-11ea-9be0-f2c9a4cc78c9.png)

```ahk
#SingleInstance, force

3paramFunc()


2paramFunc()


1paramFunc()

return

3paramFunc(param1 := "", param2 := "", param3 := "") {
    msgbox % A_ThisFunc
}

2paramFunc(param1 := "", param2 := "") {
    msgbox % A_ThisFunc
}

1paramFunc(param1 := "") {
    msgbox % A_ThisFunc
}

~^s::reload
```

**Comment by cweijan** [comment]
2.4.10 fix

**Comment by RB490** [comment]
colour is fixed, but the quotes of the first parameter are missing on 2.4.12

![image](https://user-images.githubusercontent.com/13181077/87702094-3f0d9580-c799-11ea-97df-aef4cd68bb34.png)

**Comment by cweijan** [comment]
This item will be difficult to solve, a good solution is to hide the assignment statement and only display the parameter name.

**Comment by RB490** [comment]
No problemo. Having one assignment statement missing is better then none
