### ISSUE TITLE
Running script with #include statements does not find included files

### ISSUE THREAD

**Issue by jkremp** [cweijan/autohotkey-plus#23]
Hi,
for a couple of weeks now - looks like since one of the latest updates in May or June 2020 - I cannot run my AHK script anymore using VSC and the "Run" feature. My AHK script uses `#include` statements. The error in the debug console looks like:

`#Include file "..." cannot be opened.`

Using AutoHotKey directly on the script by right click and `Run Script` it works.

Thanks for sime ideas, what I'm doing wrong.

**Comment by cweijan** [comment]
Show your ahk code, It works fine for me.

**Comment by cweijan** [comment]
Update to 2.4.11 to fix it.

**Comment by jkremp** [comment]
Works, great. Thanks.
