### ISSUE TITLE
运行路径的问题

### ISSUE THREAD

**Issue by egbertwong** [cweijan/autohotkey-plus#25]
抱歉，我也遇到了运行路径的问题
我的项目路径为:   
- ../opensourceproject
    - ahk-project
        - main.ahk
        - second.ahk

`second.ahk` is included by `main.ahk`. The content of `main.ahk` is as follows:
```ahk
#NoEnv
SendMode Input
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#Include, second.ahk

MsgBox, Hello
```

点击 Run 按钮，报错如下：  
`E:\OpenSourseProject\ahk-project\main.ahk (6) : ==> #Include file "e:\OpenSourseProject\second.ahk" cannot be opened.`   
但是在文件夹里双击 `main.ahk` 是可以正常运行的。
把 include 的内容改成 `%A_ScriptDir%/second.ahk` 的话点击 Run 才能正常运行，请问我是有哪一步做错了吗？

我打开项目的方式是：
打开 `../opensourceproject/ahk-project/` 路径，右键文件夹空白处，选择 `通过 code 打开` 

谢谢大佬的插件！！！

**Comment by cweijan** [comment]
2.4.11修复了该问题.

**Comment by egbertwong** [comment]
谢谢
