### ISSUE TITLE
Inputbox incorrect autocomplete

### ISSUE THREAD

**Issue by RB490** [cweijan/autohotkey-plus#28]
![image](https://user-images.githubusercontent.com/13181077/87709877-3cb13880-c7a5-11ea-8a6f-418c03580cca.png)

![image](https://user-images.githubusercontent.com/13181077/87709906-45a20a00-c7a5-11ea-9609-99c9e5377573.png)
font should be locale, and default is missing

**Comment by RB490** [comment]
https://www.autohotkey.com/docs/commands/InputBox.htm

**Comment by cweijan** [comment]
https://github.com/cweijan/vscode-autohotkey/blob/master/snippets/ahk.json
Change it and create pull request, I'm not use  it.

**Comment by RB490** [comment]
Done
