### ISSUE TITLE
Extra indentations on empty lines

### ISSUE THREAD

**Issue by daephx** [cweijan/autohotkey-plus#35]
So, I use the extension 'Indent-Rainbow' and to me it reveals that the formatter is generating unnecessary indentations.
I checked against powershell and python and both their formatters seem to scrub empty lines.

## Autohotkey:
![image](https://user-images.githubusercontent.com/36192863/90576713-cfae0b80-e173-11ea-8523-788a8740570f.png)

---
Format on save:

![image](https://i.imgur.com/YEMobyo.gif)

## Powershell:
![image](https://i.imgur.com/bD2X4yn.gif)

**Comment by cweijan** [comment]
Thanks feedback, update to version 2.4.16 to fix.
