### ISSUE TITLE
How to debug if the script is not opened in the VSCode Editor?

### ISSUE THREAD

**Issue by ImmortalPony** [cweijan/autohotkey-plus#36]
Hello. Thanks a lot for the great extention.
If I run the script which was not opened in the VSCode editor (editor tab is not active or even closed) then the debug panel appears, but the script is not started. If I restart Debug with corresponding command then script runs, but no breakpoints are activated.

There is no issues if I start the debug when the script is opened in the editor.

I don't know what I'm doing wrong.

Here is my "launch.json":

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ahk",
            "request": "launch",
            "name": "Autohotkey Debugger",
            "program": "${workspaceFolder}\\main.ahk",
            "stopOnEntry": true
        }
    ]
}
```

The ${workspaceFolder} is like `C:\Users\%UserName%\AAA\BBB\CCC.ahk`

Would you help me, please?

**Comment by cweijan** [comment]
Thanks feedback, update version to 2.4.15 to fix.
