### ISSUE TITLE
GoTo Definition and Find References also find them in unrelated files

### ISSUE THREAD

**Issue by Toralf-AHK** [cweijan/autohotkey-plus#38]
The GoTo Definition and Find References searches in all files in a folder and not only in the included files.
In my case the GoTo Definition shows the "wrong" function, I assume, because it finds this not included files first in the folder which happend to contain a function with the exact same name.

**Comment by cweijan** [comment]
Because the script file may be referenced by other scripts, all script functions are currently parsed in the same namespace. I have no plans to fix this problem in the near future.
