### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by boog2dan** [cweijan/autohotkey-plus#4]
Hi, love your extension, I've been using it for a couple of days.

Today, I could not debug my ahk scripts any longer.
Pls see attached screenshot - debugger is no longer showing vars or stopping at breakpoints.

https://i.imgur.com/DWfXn5T.png

Tried reinstalling VSCode, deleting extensions folders, reinstalling them.

**Comment by cweijan** [comment]
Did you press F4?

**Comment by boog2dan** [comment]
Yes, pressing F4, or any other does not trigger the BP, it just runs the script without debugger.
https://i.imgur.com/yzPWEIg.png

No matter where I put the BP, it does not stop or show any VARs.

Path to AutoHotkey, if it helps: C:\Program Files\AutoHotkey
https://i.imgur.com/Ir5Ij6V.png

**Comment by boog2dan** [comment]
Found the bug. 

If the filename has a " - " in it, the debugger will not work.

AutoHotkey Files 3 Folders.ahk.ahk (works)
AutoHotkey - Files 3 Folders.ahk (does not work)

My-Script.ahk (also works)
My - Script.ahk (does not work)
