### ISSUE TITLE
formating switch is now broken

### ISSUE THREAD

**Issue by ggrigorov** [cweijan/autohotkey-plus#41]
In version 2.5.3 the switch is formated in a wrong way 

before
<img width="386" alt="Code_3jway7c4ge" src="https://user-images.githubusercontent.com/4126064/94321192-9c8f4100-ff97-11ea-924d-4e41d0b9a71e.png">

now
<img width="386" alt="riWxRPy1ev" src="https://user-images.githubusercontent.com/4126064/94321215-aadd5d00-ff97-11ea-8d5d-80b934be6d78.png">

**Comment by cweijan** [comment]
close duplicate.
