### ISSUE TITLE
formatting switch is not working in 2.5.3

### ISSUE THREAD

**Issue by ggrigorov** [cweijan/autohotkey-plus#42]
In version 2.5.3 the switch is formated in a wrong way 

before
<img width="386" alt="Code_3jway7c4ge" src="https://user-images.githubusercontent.com/4126064/94321192-9c8f4100-ff97-11ea-924d-4e41d0b9a71e.png">

now
<img width="386" alt="riWxRPy1ev" src="https://user-images.githubusercontent.com/4126064/94321215-aadd5d00-ff97-11ea-8d5d-80b934be6d78.png">

**Comment by fade2gray** [comment]
I have no problem using the formating command in 2.5.3 - perhaps there could be a conflict with another extension?

**Comment by ggrigorov** [comment]
I don't have any other extension but AH Plus

running on Windows 10 x64 | VCode 1.49.2 (user setup)

![oRf2M6DzFl](https://user-images.githubusercontent.com/4126064/94350588-36b6be00-0058-11eb-8d27-11be30077b0c.gif)

**Comment by cweijan** [comment]
Hi, try using version 2.5.4.

**Comment by ggrigorov** [comment]
> Hi, try using version 2.5.4.

@cweijan thank you so much. It works great!

:) kudos
