### ISSUE TITLE
Enhancement: Region-folding

### ISSUE THREAD

**Issue by Hicsy** [cweijan/autohotkey-plus#44]
Gday
### PR:
My pull-request with the solution can be found here: https://github.com/cweijan/vscode-autohotkey/pull/43

### Proposal:
Other languages generally have regions folding marked by a comment which starts with the work `region` .
This will then be folded up until the corresponding comment beginning with `endregion`.

I understand that this might already be implemented elsewhere in your code that i missed, or perhaps it has been left out for a reason (_stale request upstream, awaiting official input, awaiting v2 etc etc_).
 Feel free to ping me if you need any further clarification.

I have provided [examples in the Pull Request](https://github.com/cweijan/vscode-autohotkey/pull/43#issuecomment-699492727).

Cheers

**Comment by Hicsy** [comment]
### Potential minor issue:
If a madman [changes their comment indicator](https://www.autohotkey.com/docs/commands/_CommentFlag.htm) this will obviously not be usable by that script.
This is no issue in the upcoming AHKv2 as they removed this dangerous Directive.

**Comment by cweijan** [comment]
Has been merge, will release on next version.
