### ISSUE TITLE
launch AHK help

### ISSUE THREAD

**Issue by ElectroLund** [cweijan/autohotkey-plus#55]
Would be great to open the help file AutoHotkey.chm from within VSCode.

**Comment by cweijan** [comment]
version 2.6.0 has been support, when active editor language is autohotkey, press F1 to open document.

**Comment by fade2gray** [comment]
This overrides VSCode's default keybinding `Show All Commands` for opening the `Command Palette` that I'd gotten so used to.

Can't it be changed to `Shift + F1`, I don't see that being use as a default keybinding, or just leave it to be accessed from the command palette with `AHK: Open AutoHotkey Document`?

**Comment by cweijan** [comment]
@fade2gray 
1. press ctrl+shift+p
2. type 'open keyboard shortcuts' 
3. Add below code to keybindings.json 
```json
{
        "key": "shift+f1",
        "command": "document.open",
        "when": "editorLangId == 'ahk'"
}
```
