### ISSUE TITLE
Formatter adds indentation on "for" even if just a string

### ISSUE THREAD

**Issue by ewerybody** [cweijan/autohotkey-plus#58]
### Found:
try to format this:
```ahk
InputBox, name, for bla
if somthing
    Return
```
it will turn to:
```ahk
InputBox, name, for bla
    if somthing ; << indentation added!
    Return
```
### Expected:
There is actually no change expected.
It seems to be triggered on the `for` keyword!

**Comment by FuPeiJiang** [comment]
if you need it now, I've fixed it in my fork, https://github.com/FuPeiJiang/vscode-autohotkey-plus-plus/tree/bad-for-indent
but pull requests are complicated...

should I commit the out folder ? (minified using Closure Compiler)

**Comment by ewerybody** [comment]
Ah nice! But whats the problem, PRs not welcome or what?

**Comment by FuPeiJiang** [comment]
1st, I can't PR, my repo is a fork of a fork
I will PR to ahk++, since it's probably the most active ?

**Comment by ewerybody** [comment]
Ah cool! I didn't know that! I just saw that this one here has the most downloads. ++ is still just in the hundreds. But I'll give it a spin :) thank you! 

(also looking forward contributing to extensions myself ... currently I'm not into that)

**Comment by mark-wiemer** [comment]
Hiya, maintainer of [AHK++](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus#readme) here! I started the project in November when `cweijan` announced they (unsure of pronouns, sticking with neutral) had [stopped development on AHK Plus](https://github.com/AutoHotkey-Plus/vscode-autohotkey/commit/e87f12774692d4c0d792650c099e6071dc17b069). Clearly, they've picked it up again, which is great. I plan to work with them to figure out the best way forward for AHK Language Support in VS Code. In the meantime, I'll be working to merge changes to AHK Plus into AHK++ (along with additional changes to AHK++).

Looking forward to reviewing your PRs, feel free to ask for help any time :)

**Comment by ewerybody** [comment]
Hey @mark-wiemer! Nice! Starting off a different Extension I imagine to be hard. But good you'd been talking tho. I'd be happy to help!

**Comment by mark-wiemer** [comment]
If you still want this issue fixed, please open an issue in [my fork](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus), and I'll look into it! It's easier to track one repo only. I have been making some changes to the formatter recently, so something like this shouldn't be too hard. I'm prioritizing dev QoL right now (no new features or bugfixes, just refactors and adding tests), but I should be able to get to it in March at the latest

**Comment by mark-wiemer** [comment]
Closed in v3 :)
