### ISSUE TITLE
formatting issue indenting in the wrong place

### ISSUE THREAD

**Issue by Wilson703** [cweijan/autohotkey-plus#73]
basically the issue goes like this if you have an "if" in the msgbox line it will indent the row underneath

and format it like this
```
a() {
    Msgbox, if the problem....
    }
```
remove that "if"
and it indents correctly

```
a() {
    Msgbox, the problem....
}
```

here is a link to a video displaying the problem
https://i.imgur.com/pDES4Az.gif

**Comment by mark-wiemer** [comment]
Closed in v3.0.0 and [AHK++ v3.1.0](https://github.com/vscode-autohotkey/vscode-autohotkey-plus-plus/releases/tag/v3.1.0)
