### ISSUE TITLE
Debugging failure after restarting vscode

### ISSUE THREAD

**Issue by zero-plusplus** [cweijan/autohotkey-plus#8]
**By Google Translate from Japanese to English.**

If you start debugging in the following way, it will fail.
1. "program" is set to something other than "$ {file}"
2. Restart vscode without opening the file set in "program"
3. Start debugging

Curiously, if you open and close the file set in "program" and start debugging, it works fine.

**Comment by cweijan** [comment]
These failure flow is normal.
When program is null, [ScriptRunner](https://github.com/cweijan/vscode-autohotkey/blob/edcaf8ada599ce57087b959822e7e71e00d65402/src/core/ScriptRunner.ts#L41) will get current open file.

**Comment by zero-plusplus** [comment]
**By Google Translate from Japanese to English.**

sorry. My intentions have not been correctly communicated.

This is definitely a bug. "path" is not null. And are properly specified.
In the first place, it fails before it reaches [AhkDebugSession constructor](https://github.com/cweijan/vscode-autohotkey/blob/master/src/debugger/AhkDebug.ts#L56).

The conditions for this bug are as follows.
You can check this using the "Autohotkey v1 Debugger" debug configuration of this repository.
1. Launch vscode newly
2. Start debugging without having activated the file with the extension "ahk"

**Comment by cweijan** [comment]
I got you mean. In your situation, the plugin is not active.
Fix at add [onDebug](https://github.com/cweijan/vscode-autohotkey/blob/e2f526b62b05953b7d341f525cf173ad8cef268e/package.json#L15) to activationEvents of package.json .

**Comment by zero-plusplus** [comment]
Thanks!

**Comment by zero-plusplus** [comment]
**By Google Translate from Japanese to English.**

I am new to using "issues".
Should it be open until there is a fix?

**Comment by zero-plusplus** [comment]
I confirmed the fix. Thanks!
