### ISSUE TITLE
Failed to inspect instance of class in "demo_for_ahk_v2"

### ISSUE THREAD

**Issue by zero-plusplus** [cweijan/autohotkey-plus#9]
**By Google Translate from Japanese to English.**

The conditions are as follows.
1. Start debugging `demo_for_ahk_v2`
2. Expand the Global list.
3. Break at the line after `instance: = new Cls()`

Then the following error message is displayed.
`Command failed: "C:\Program Files\AutoHotkey\v2-alpha\x64\AutoHotkey.exe" /debug=localhost:9001 "W:\project\vscode-autohotkey/demos/demo_for_ahk_v2.ahk"`

**Comment by cweijan** [comment]
You can try fix it, I don't use Ahk V2.

**Comment by zero-plusplus** [comment]
ok. I will try.
